name: build-mrs

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Aggregate IPCIDR lists
        run: |
          mkdir -p build

          cat ASN/Alfa-Bank/*.ipcidr \
            | sort -u > build/Alfa-Bank.ipcidr

          cat ASN/Kontur/*.ipcidr \
            | sort -u > build/Kontur.ipcidr

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile MRS using official mihomo image
        run: |
          docker run --rm \
            -v "$PWD:/data" \
            ghcr.io/metacubex/mihomo:v1.19.19 \
            rule-set compile --type ipcidr \
            --input /data/build/Alfa-Bank.ipcidr \
            --output /data/Alfa-Bank.mrs

          docker run --rm \
            -v "$PWD:/data" \
            ghcr.io/metacubex/mihomo:v1.19.19 \
            rule-set compile --type ipcidr \
            --input /data/build/Kontur.ipcidr \
            --output /data/Kontur.mrs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mrs
          path: |
            Alfa-Bank.mrs
            Kontur.mrs
